"""Scout writer — format pain points as readable Markdown brief.
"""
from __future__ import annotations

from typing import Any

from datetime import datetime, timezone


def format_brief_markdown(
    date_str: str,
    pain_points: list[dict[str, Any]],
    raw_data_summary: dict[str, int],
    llm_usage: dict[str, Any] | None = None,
) -> str:
    """Format pain points into a structured Markdown brief.

    Layout:
    - Top 3 critical (build ngay)
    - Top 4-10 worth tracking
    - Source coverage stats
    - Recommendation
    """
    top3 = [pp for pp in pain_points if pp["severity"] >= 7][:3]
    rest = [pp for pp in pain_points if pp not in top3][:7]

    lines = [
        f"# Scout Brief — {date_str}",
        "",
        f"**Generated:** {datetime.now(timezone.utc).isoformat(timespec='seconds')}",
        f"**Total pain points:** {len(pain_points)}",
        f"**Top severity:** {pain_points[0]['severity'] if pain_points else 0}/10",
        "",
        "---",
        "",
    ]

    # Top 3 critical
    lines.append("## 🔥 Top 3 — Critical (build ngay)")
    lines.append("")
    if not top3:
        lines.append("_Không có pain point severity ≥ 7 trong data hôm nay._")
        lines.append("")
    for i, pp in enumerate(top3, 1):
        lines.extend(_format_pain_point(i, pp, critical=True))

    # Rest worth tracking
    lines.append("## 📊 Top 4-10 — Worth tracking")
    lines.append("")
    if not rest:
        lines.append("_Không có pain point severity 5-6 trong data hôm nay._")
        lines.append("")
    for i, pp in enumerate(rest, len(top3) + 1):
        lines.extend(_format_pain_point(i, pp, critical=False))

    # Source coverage
    lines.append("## 📡 Source coverage")
    lines.append("")
    lines.append("| Source | Hits |")
    lines.append("|---|---|")
    for src, count in raw_data_summary.items():
        lines.append(f"| {src} | {count} |")
    total = sum(raw_data_summary.values())
    lines.append(f"| **Total** | **{total}** |")
    lines.append("")

    # Recommendation
    lines.append("## 🎯 Recommendation")
    lines.append("")
    if top3:
        first = top3[0]
        lines.append(
            f"**Nên build:** _{first['title']}_ — severity {first['severity']}/10, "
            f"~{first.get('market_size_vn', 'N/A')} người VN, "
            f"est. {first.get('estimated_monthly_revenue_vnd', 0):,} VNĐ/tháng."
        )
    else:
        lines.append("**Nên chờ data tuần sau** — không có pain point critical trong batch hôm nay.")
    lines.append("")

    # LLM usage
    if llm_usage:
        lines.append("## 🤖 LLM usage")
        lines.append("")
        lines.append(f"- Model: `{llm_usage.get('model', 'unknown')}`")
        lines.append(f"- Tokens: {llm_usage.get('input_tokens', 0)} in / {llm_usage.get('output_tokens', 0)} out")
        lines.append(f"- Latency: {llm_usage.get('latency_ms', 0)}ms")
        lines.append("")

    lines.append("---")
    lines.append("_Auto-generated by Scout. Owner: review top 3, queue 1 to Architect._")

    return "\n".join(lines)


def _format_pain_point(idx: int, pp: dict[str, Any], critical: bool) -> list[str]:
    """Format 1 pain point as Markdown block."""
    severity_badge = "🔥" * (pp["severity"] // 2) + "·" * (5 - pp["severity"] // 2)
    lines = [
        f"### {idx}. {pp['title']} [{pp['severity']}/10 {severity_badge}]",
        "",
        f"**{pp.get('description', 'N/A')}**",
        "",
        f"- 🎯 **Audience:** {pp.get('audience', 'N/A')}",
        f"- 📊 **Market size (VN):** {pp.get('market_size_vn', 'N/A')}",
        f"- 💰 **Est. monthly revenue:** {pp.get('estimated_monthly_revenue_vnd', 0):,} VNĐ",
        f"- 🔧 **Effort (ToolForge):** {pp.get('opportunity', 'N/A')}",
        f"- 📌 **Current solutions:** {pp.get('current_solutions', 'N/A')}",
        f"- ⚠️ **Gap:** {pp.get('gap', 'N/A')}",
    ]
    sources = pp.get("source_signals", [])
    if sources:
        lines.append(f"- 🔗 **Signals:**")
        for s in sources[:3]:
            lines.append(f"  - {s}")
    lines.append("")
    return lines


def format_top_pain_json(pain_points: list[dict[str, Any]]) -> str:
    """Format pain points as compact JSON (for D1 top_pain_json column)."""
    import json
    compact = []
    for pp in pain_points:
        compact.append({
            "title": pp.get("title", ""),
            "severity": pp.get("severity", 0),
            "audience": pp.get("audience", ""),
            "market_size_vn": pp.get("market_size_vn", ""),
            "opportunity": pp.get("opportunity", ""),
        })
    return json.dumps(compact, ensure_ascii=False)
