// ToolForge App library - Tauri 2.x
// Generated by Forge agent. Customize commands for your tool.

use serde::{Deserialize, Serialize};

#[derive(Debug, Serialize, Deserialize, Clone)]
pub struct ToolInfo {
    pub name: String,
    pub version: String,
    pub description: String,
    pub license_key: String,
}

#[tauri::command]
fn get_tool_info() -> ToolInfo {
    ToolInfo {
        name: env!("CARGO_PKG_NAME").to_string(),
        version: env!("CARGO_PKG_VERSION").to_string(),
        description: env!("CARGO_PKG_DESCRIPTION").to_string(),
        license_key: "PLACEHOLDER_LICENSE_KEY".to_string(),
    }
}

#[tauri::command]
fn verify_license(license_key: String) -> bool {
    // TODO: Call /api/license/verify to check license validity
    // For now: simple format check (XXXX-XXXX-XXXX-XXXX)
    license_key.split('-').count() == 4
        && license_key.split('-').all(|p| p.len() == 4 && p.chars().all(|c| c.is_ascii_hexdigit()))
}

#[tauri::command]
fn ping() -> String {
    "pong".to_string()
}

#[cfg_attr(mobile, tauri::mobile_entry_point)]
pub fn run() {
    tauri::Builder::default()
        .plugin(tauri_plugin_shell::init())
        .invoke_handler(tauri::generate_handler![get_tool_info, verify_license, ping])
        .run(tauri::generate_context!())
        .expect("error while running tauri application");
}
