// ToolForge App - Tauri 2.x entry point
// Generated by Forge agent. Customize commands for your tool.

#![cfg_attr(not(debug_assertions), windows_subsystem = "windows")]

fn main() {
    toolforge_app_lib::run();
}
